### PR TITLE
Update tolerance and tests

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
Fix tolerance for the analytical state test, and update tests results. Does it work on your machines @andreapiacentini?

### CODE REVIEW

**Comment by andreapiacentini** [comment]
Nope...
When test_aq_parameters_loc_6pe passes, the 3d tests now succeed.
The 4d not yet (I guess a similar fix on the expected values or on the relaxation of the tolerance would do the trick).
Yet the main problem (by far more worrying) is the random failure of the test_aq_parameters_loc_6pe or 2pe

**Comment by benjaminmenetrier** [comment]
All tests pass on my workstation for GNU 10.3.0 and Intel 2021.5.0.

**Comment by andreapiacentini** [comment]
With intel 2021.5.0 I have differences between log ant test for the 4d dirac loc and the 4densvar.
With intel 2018 (the production version on nemo), I've submitted a 10 times repetition of ctest -R test_aq_parameters and got the following 5 outputs with the 6th repetition hanging indefinetely in test_aq_parameters_loc_6pe.
It would deserve an analysis, yet I don't know how to compile only saber / aq in debug mode but not atlas (the compiler fails on some fortran modules)

Test project /scratch/ae/emili/seeds_crontest/code/build
    Start 640: test_aq_parameters_loc_6pe
1/2 Test #640: test_aq_parameters_loc_6pe .......***Failed   11.23 sec
    Start 647: test_aq_parameters_loc_2pe
2/2 Test #647: test_aq_parameters_loc_2pe .......   Passed   13.41 sec

Test project /scratch/ae/emili/seeds_crontest/code/build
    Start 640: test_aq_parameters_loc_6pe
1/2 Test #640: test_aq_parameters_loc_6pe .......   Passed   10.01 sec
    Start 647: test_aq_parameters_loc_2pe
2/2 Test #647: test_aq_parameters_loc_2pe .......   Passed   13.24 sec

Test project /scratch/ae/emili/seeds_crontest/code/build
    Start 640: test_aq_parameters_loc_6pe
1/2 Test #640: test_aq_parameters_loc_6pe .......***Failed    9.74 sec
    Start 647: test_aq_parameters_loc_2pe
2/2 Test #647: test_aq_parameters_loc_2pe .......   Passed   13.42 sec

Test project /scratch/ae/emili/seeds_crontest/code/build
    Start 640: test_aq_parameters_loc_6pe
1/2 Test #640: test_aq_parameters_loc_6pe .......   Passed   10.11 sec
    Start 647: test_aq_parameters_loc_2pe
2/2 Test #647: test_aq_parameters_loc_2pe .......***Failed   12.29 sec

Test project /scratch/ae/emili/seeds_crontest/code/build
    Start 640: test_aq_parameters_loc_6pe
1/2 Test #640: test_aq_parameters_loc_6pe .......   Passed   10.11 sec
    Start 647: test_aq_parameters_loc_2pe
2/2 Test #647: test_aq_parameters_loc_2pe .......   Passed   13.17 sec

**Comment by andreapiacentini** [comment]
Got this traceback
```
forrtl: severe (173): A pointer passed to DEALLOCATE points to an object that cannot be deallocated
Image              PC                Routine            Line        Source             
libifcoremt.so.5   00002B86E3D40E58  for_dealloc_alloc     Unknown  Unknown
libsaber.so        00002B86D2B149A0  type_linop_mp_lin         148  type_linop.F90
libsaber.so        00002B86D2B6AD97  type_nicas_blk_mp         513  type_nicas_blk.F90
libsaber.so        00002B86D2BC829E  type_nicas_mp_nic         169  type_nicas.F90
libsaber.so        00002B86D2BD7E45  type_nicas_mp_nic         870  type_nicas.F90
libsaber.so        00002B86D29F9322  type_bump_mp_bump         806  type_bump.F90
libsaber.so        00002B86D28FDC48  bump_run_drivers_         201  type_bump_interface.F90
aq_error_covarian  00000000004CC09B  _ZNK5saber4BUMPIN         962  BUMP.h
aq_error_covarian  00000000004C8A1E  _ZN5saber4BUMPIN2         772  BUMP.h
aq_error_covarian  0000000000500BD6  _ZNK5saber23Error         181  ErrorCovarianceTraining.h
liboops.so         00002B86D701A5BE  Unknown               Unknown  Unknown
aq_error_covarian  0000000000413CD6  main                       21  aqErrorCovarianceTraining.cc
libc-2.17.so       00002B86E36D9B35  __libc_start_main     Unknown  Unknown
aq_error_covarian  0000000000413669  Unknown               Unknown  Unknown
```

**Comment by andreapiacentini** [comment]
About the differences I've with Intel 21 and you have not, I am wondering if you are running TIER 2 tests.

And about the failures with intel18, they happen at different moments at every failing run. Somehow I'd say that the higher the number of processes, the easier the failure, but it's not really a statistics.

**Comment by benjaminmenetrier** [comment]
Correct, the tier 2 was not activated. I've updated tier 2 tests references. All tests pass for:
- GNU with `RelWithDebInfo` build,
- GNU with `debug` build,
- Intel with `RelWithDebInfo` build.

I never had any runtime failure, sorry...

**Review by andreapiacentini — APPROVED** [review]
Provided we have a recent compiler enough (younger than intel 18) it works.

**Pull request merged**
