### PR TITLE
Groups of variables in BUMP

### PR DESCRIPTION
**Pull request by benjaminmenetrier**
## Description

Companion PR of https://github.com/JCSDA-internal/saber/pull/424
AQ is not forgotten this time!

### CODE REVIEW

**Comment by andreapiacentini** [comment]
AQ is very grateful.  
@benjaminmenetrier thanks for this.  
I noticed in the v2 document that correlations amongst groups are neglected but for the `crossed` (I hope not in the common usage meaning of being both drunk and under the effect of drugs) strategy.  
For the `duplicated and weighted` strategy in atmospheric chemistry (please @emanueleemili elaborate on it if you feel the need) we could ideally split the variables in _groups_ (e.g. aerosols families, chemical components categorized by lifespan, etc) and weight off differently the cross-correlations among groups. Yet we rather planned to simply create sublists of variables and use them in the `row variables`  and `column variables` entries of nicas settings.  
If you thought of _groups_ as something to be used in this kind of situations, we could elaborate on it (probably needing an optional `name` entry for the groups), otherwise we are happy with what we have.  
About the v2 document, I have a couple of remarks, but I’ll send you an annotated pdf by mail.

**Comment by andreapiacentini** [comment]
[multivariate_localization.pdf](https://github.com/andreapiacentini/aq/files/10444500/multivariate_localization.pdf)
@benjaminmenetrier I hope my comments are visible in the attached file

**Comment by benjaminmenetrier** [comment]
They are, thanks.

**Review by andreapiacentini — APPROVED** [review]

**Review by andreapiacentini — APPROVED** [review]

**Comment by benjaminmenetrier** [comment]
@andreapiacentini: I've addressed your comments in the latest version of the note.
- I agree that "no cross-localization" can be confusing, so I use "zero cross-localization" for clarity.
- In the latest case, all the components `U_q` are in the same column, so the control vector size is `\bar{m}` and not `Q \bar{m}`.

**Comment by benjaminmenetrier** [comment]
The `groups` structure was not really intended for your case, more for the `duplicated` case.

**Comment by andreapiacentini** [comment]
> * In the latest case, all the components `U_q` are in the same column, so the control vector size is `\bar{m}` and not `Q \bar{m}`.

I understand and it is clear when comparing equations (11) and (7)

**Comment by benjaminmenetrier** [comment]
This PR can be merged now.

**Pull request merged**
